config/routes.rb
VoupeShort::Application.routes.draw do

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions

  match ":short" => "urls#goto"
  
  root :to => "home#index"

  namespace :admin do
    resources :sites
    resources :urls do
      member {get :clicks}
    end
    resources :clicks
  end

  namespace :api do
  	match ":site_uuid/urls" => "urls#index"
  	match ":site_uuid/urls/new" => "urls#new"
  end

end

app/models/click.rb
class Click < ActiveRecord::Base
  
  attr_accessible :ip_address, :referrer, :url_id, :user_agent

  belongs_to :url

  default_scope :order => "id DESC"

end

app/models/site.rb
class Site < ActiveRecord::Base
  
  attr_accessible :domain, :name

  has_many :urls

  validates_uniqueness_of :domain, :name
  validates_presence_of :domain, :name

  before_create {
  	self.uuid = SecureRandom.uuid
  }

end

app/models/url.rb
class Url < ActiveRecord::Base

  attr_accessible :long_url, :short, :site_id

  belongs_to :site
  has_many :clicks, :dependent => :destroy

  validates_uniqueness_of :long_url, :scope => :site_id
  validates_uniqueness_of :short
  validates_presence_of :site, :long_url, :short
  format_url :long_url

  default_scope :order => "id DESC"

  before_validation :generate_short

  scope :search, lambda { |search| where("long_url LIKE ? OR short LIKE ?", "%#{search}%", "%#{search}%")}

  def full_short_link
  	"http://#{self.site.domain}/#{self.short}"  	
  end

  # customised as_json call
  def as_json(options={})
    { :id => id, :full_url => full_short_link, :short => short, :long_url => long_url, :title => title }
  end

	private

	def generate_short
		begin
			self.short = SecureRandom.hex(2)
		end while self.class.exists?(short: short)
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_secure_password
  
	attr_accessible :email, :password, :password_confirmation
  
	validates_uniqueness_of :email

end

app/controllers/admin/urls_controller.rb
class Admin::UrlsController < ApplicationController

	before_filter :authorize

	def index
		@title = "All URLs"
		@urls = Url.search(params[:search]).paginate(:page => params[:page])
	end

	def destroy
		@url = Url.find(params[:id])
		@url.destroy		
		redirect_to admin_site_path(@url.site), :notice => "URL Deleted Successfully"
	end

	def clicks
		@url = Url.find(params[:id])
		@clicks = @url.clicks
		@title = "Clicks for #{@url.full_short_link}"
	end

end

app/controllers/api/base_controller.rb
class Api::BaseController < ApplicationController

	respond_to :json

end

app/controllers/api/urls_controller.rb
class Api::UrlsController < Api::BaseController

	before_filter do
		@site = Site.find_by_uuid(params[:site_uuid])

		render :text => "Error. Site not found." unless @site
	end

	# display a paginated list of urls for a site
	def index
		@urls = @site.urls.paginate(:page => params[:page])
		respond_with @urls
	end

	# create a new url linked to a site
	def new

    if params[:url].blank?
	    render :text => "URL not passed as a variable" 
    else
    	uri = URI::parse(params[:url])

	    # check to see if there's an existing short url
	    short_url = @site.urls.find_by_short(uri.path.split('/').second) || @site.urls.find_by_long_url(params[:url]) || @site.urls.find_by_long_url("http://#{params[:url]}")

	    if short_url
	      respond_to do |format|
		      format.html { render :text => short_url.full_short_link }
		      format.json { respond_with short_url }
		    end
	    else
	      @url = @site.urls.create(long_url: params[:url])
	      # Rails.logger.info request.path

	      respond_to do |format|
		      format.html { render :text => @url.full_short_link }
		      format.json { respond_with @url }
		    end
	    end
	  end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery

	private

	def current_user
	  @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	helper_method :current_user

	def current_site
    @site ||= Site.find_by_domain(request.host)
  end
  helper_method :current_site

	def authorize
	  redirect_to login_url, alert: "Not authorized" if current_user.nil?
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		render :text => "Voupe Short"		
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	before_filter :authorize, :except => [:new, :create]

	layout "login"

	def new
	end

	def create
	  user = User.find_by_email(params[:email])
	  if user && user.authenticate(params[:password])
	    session[:user_id] = user.id
	    redirect_to admin_sites_path, notice: "Logged in!"
	  else
	    flash.now.alert = "Email or password is invalid"
	    render "new"
	  end
	end

	def destroy
	  session[:user_id] = nil
	  redirect_to login_url, notice: "Logged out!"
	end

end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController

	# GET /:short
  # Sends the user to the desired link and increments the click counter
  def goto
    url = current_site.urls.find_by_short(params[:short])

    if url
    	Click.create(:url_id => url.id, :referrer => request.referer, :user_agent => request.user_agent, :ip_address => request.ip)
      redirect_to url.long_url
    else
    	render :text => "URL not found", :status => 404
    	# render :file => "#{Rails.root}/public/404.html", :status => :not_found
    end
  end

end

app/helpers/admin/clicks_helper.rb
module Admin::ClicksHelper
end

app/helpers/admin/sites_helper.rb
module Admin::SitesHelper
end

app/helpers/admin/urls_helper.rb
module Admin::UrlsHelper
end

app/helpers/api/base_helper.rb
module Api::BaseHelper
end

app/helpers/api/urls_helper.rb
module Api::UrlsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/_messages.html.haml
- if flash[:success] or flash[:notice]
	.alert.alert-success
		= raw flash[:success] || flash[:notice]
- if flash[:error] or flash[:alert]
	.alert.alert-error
		= raw flash[:error] || flash[:alert]

app/views/layouts/_navigation.html.haml
= link_to "Voupe Short", admin_sites_path, :class => "brand"
.nav-collapse.collapse
	%ul.nav
		%li.dropdown
			%a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
				Sites
				%b.caret
			%ul.dropdown-menu
				%li= link_to "New Site", new_admin_site_path
				%li.divider
				- Site.all.each do |site|
					%li= link_to raw("<b>#{site.name} - #{site.domain}</b> (#{site.urls.size})"), admin_site_path(site)
		%li= link_to "URLs", admin_urls_path
		%li= link_to "Clicks", admin_clicks_path

	%p.navbar-text.pull-right
		= link_to "Logged in as #{current_user.email}", logout_path, :class => "navbar-link", :title => "Logout"

app/views/layouts/application.html.haml
!!!
%html
	%head
		%meta{:charset => "utf-8"}/
		%meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
		%title Voupe Short - #{@title}
		= stylesheet_link_tag    "application", :media => "all"
		= javascript_include_tag "application"
		= csrf_meta_tags
	%body
		.navbar.navbar-inverse.navbar-fixed-top
			.navbar-inner
				.container
					= render "layouts/navigation"

		.main_content.container
			= render 'layouts/messages'
			.page-header
				%h2 #{@title} <small>#{@subtitle}</small>
				= yield :title_header

			= yield

	- if Rails.env.development?
		<script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')</script>

app/views/layouts/login.html.haml
!!!
%html
	%head
		%meta{:charset => "utf-8"}/
		%meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
		%title Voupe Exceptions - #{@title}
		= stylesheet_link_tag    "application", :media => "all"
		= javascript_include_tag "application"
		= csrf_meta_tags
	%body.login_layout
		.form-signin
			= render "layouts/messages"
			= yield

	- if Rails.env.development?
		<script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')</script>