config/routes.rb
VoupeShort::Application.routes.draw do

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions

  match ":short" => "urls#goto"
  
  root :to => "home#index"

  namespace :admin do
    resources :sites
    resources :urls do
      member {get :clicks}
    end
    resources :clicks
  end

  namespace :api do
  	match ":site_uuid/urls" => "urls#index"
  	match ":site_uuid/urls/new" => "urls#new"
  end

end

app/models/click.rb
class Click < ActiveRecord::Base
  
  attr_accessible :ip_address, :referrer, :url_id, :user_agent

  belongs_to :url

  default_scope :order => "id DESC"

end

app/models/site.rb
class Site < ActiveRecord::Base
  
  attr_accessible :domain, :name

  has_many :urls

  validates_uniqueness_of :domain, :name
  validates_presence_of :domain, :name

  before_create {
  	self.uuid = SecureRandom.uuid
  }

end

app/models/url.rb
class Url < ActiveRecord::Base

  attr_accessible :long_url, :short, :site_id

  belongs_to :site
  has_many :clicks, :dependent => :destroy

  validates_uniqueness_of :long_url, :scope => :site_id
  validates_uniqueness_of :short
  validates_presence_of :site, :long_url, :short
  format_url :long_url

  default_scope :order => "id DESC"

  before_validation :generate_short

  scope :search, lambda { |search| where("long_url LIKE ? OR short LIKE ?", "%#{search}%", "%#{search}%")}

  def full_short_link
  	"http://#{self.site.domain}/#{self.short}"  	
  end

  # customised as_json call
  def as_json(options={})
    { :id => id, :full_url => full_short_link, :short => short, :long_url => long_url, :title => title }
  end

	private

	def generate_short
		begin
			self.short = SecureRandom.hex(2)
		end while self.class.exists?(short: short)
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_secure_password
  
	attr_accessible :email, :password, :password_confirmation
  
	validates_uniqueness_of :email

end

app/controllers/admin/clicks_controller.rb
class Admin::ClicksController < ApplicationController

	before_filter :authorize

	def index
		@title = "All Clicks"
		@clicks = Click.paginate(:page => params[:page], :per_page => 30)
	end

end

app/controllers/admin/sites_controller.rb
class Admin::SitesController < ApplicationController

  before_filter :authorize

  def index
    @sites = Site.all
    @title = "All Sites"
  end

  def show
    @site = Site.find(params[:id])
    @urls = @site.urls.search(params[:search]).paginate(:page => params[:page])
    @title = @site.domain
    @subtitle = @site.uuid
  end

  def new
    @site = Site.new
    @title = "New Site"
  end

  def edit
    @site = Site.find(params[:id])
    @title = "Editing #{@site.domain}"
  end

  def create
    @site = Site.new(params[:site])

    if @site.save
      redirect_to admin_site_path(@site), notice: 'Site was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @site = Site.find(params[:id])

    if @site.update_attributes(params[:site])
      redirect_to admin_site_path(@site), notice: 'Site was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @site = Site.find(params[:id])
    @site.destroy

    redirect_to admin_sites_url
  end

end

app/controllers/admin/urls_controller.rb
class Admin::UrlsController < ApplicationController

	before_filter :authorize

	def index
		@title = "All URLs"
		@urls = Url.search(params[:search]).paginate(:page => params[:page])
	end

	def destroy
		@url = Url.find(params[:id])
		@url.destroy		
		redirect_to admin_site_path(@url.site), :notice => "URL Deleted Successfully"
	end

	def clicks
		@url = Url.find(params[:id])
		@clicks = @url.clicks
		@title = "Clicks for #{@url.full_short_link}"
	end

end

app/controllers/api/base_controller.rb
class Api::BaseController < ApplicationController

	respond_to :json

end

app/controllers/api/urls_controller.rb
class Api::UrlsController < Api::BaseController

	before_filter do
		@site = Site.find_by_uuid(params[:site_uuid])

		render :text => "Error. Site not found." unless @site
	end

	# display a paginated list of urls for a site
	def index
		@urls = @site.urls.paginate(:page => params[:page])
		respond_with @urls
	end

	# create a new url linked to a site
	def new

    if params[:url].blank?
	    render :text => "URL not passed as a variable" 
    else
    	uri = URI::parse(params[:url])

	    # check to see if there's an existing short url
	    short_url = @site.urls.find_by_short(uri.path.split('/').second) || @site.urls.find_by_long_url(params[:url]) || @site.urls.find_by_long_url("http://#{params[:url]}")

	    if short_url
	      respond_to do |format|
		      format.html { render :text => short_url.full_short_link }
		      format.json { respond_with short_url }
		    end
	    else
	      @url = @site.urls.create(long_url: params[:url])
	      # Rails.logger.info request.path

	      respond_to do |format|
		      format.html { render :text => @url.full_short_link }
		      format.json { respond_with @url }
		    end
	    end
	  end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery

	private

	def current_user
	  @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	helper_method :current_user

	def current_site
    @site ||= Site.find_by_domain(request.host)
  end
  helper_method :current_site

	def authorize
	  redirect_to login_url, alert: "Not authorized" if current_user.nil?
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		render :text => "Voupe Short"		
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	before_filter :authorize, :except => [:new, :create]

	layout "login"

	def new
	end

	def create
	  user = User.find_by_email(params[:email])
	  if user && user.authenticate(params[:password])
	    session[:user_id] = user.id
	    redirect_to admin_sites_path, notice: "Logged in!"
	  else
	    flash.now.alert = "Email or password is invalid"
	    render "new"
	  end
	end

	def destroy
	  session[:user_id] = nil
	  redirect_to login_url, notice: "Logged out!"
	end

end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController

	# GET /:short
  # Sends the user to the desired link and increments the click counter
  def goto
    url = current_site.urls.find_by_short(params[:short])

    if url
    	Click.create(:url_id => url.id, :referrer => request.referer, :user_agent => request.user_agent, :ip_address => request.ip)
      redirect_to url.long_url
    else
    	render :text => "URL not found", :status => 404
    	# render :file => "#{Rails.root}/public/404.html", :status => :not_found
    end
  end

end

app/helpers/admin/clicks_helper.rb
module Admin::ClicksHelper
end

app/helpers/admin/sites_helper.rb
module Admin::SitesHelper
end

app/helpers/admin/urls_helper.rb
module Admin::UrlsHelper
end

app/helpers/api/base_helper.rb
module Api::BaseHelper
end

app/helpers/api/urls_helper.rb
module Api::UrlsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/admin/clicks/_click.html.haml
= content_tag_for(:tr, click) do
	%td= link_to click.url.short, click.url.full_short_link
	%td= click.ip_address
	%td.referrer
		%p= click.referrer
	%td.user_agent
		%p= click.user_agent
	%td= click.created_at.strftime("%e/%m/%y - %H:%M")

app/views/admin/clicks/index.html.haml
%table.table.table-striped.table-bordered
	%thead
		%tr
			%th URL
			%th IP Address
			%th Referrer
			%th User Agent
			%th Date/Time
	%tbody
		= render @clicks

= will_paginate @clicks

app/views/admin/sites/_form.html.haml
- if @site.errors.any?
	#error_explanation
		%h3= "#{pluralize(@site.errors.count, "error")} prohibited this site from being saved:"
		%ul
			- @site.errors.full_messages.each do |msg|
				%li= msg

.field
	= f.label :name
	= f.text_field :name
.field
	= f.label :domain
	= f.text_field :domain
.actions
	= f.submit 'Save'

app/views/admin/sites/edit.html.haml
= form_for @site, :url => admin_site_path(@site) do |f|
	= render :partial => 'form', :locals => {:f => f}

app/views/admin/sites/index.html.haml
- content_for :title_header do
	= link_to 'New Site', new_admin_site_path, :class => "btn", :style => "float: right; position: relative; top: -45px;"

%table.table.table-striped.table-bordered
	%thead
		%tr
			%th Name
			%th UUID
			%th Domain
			%th
	%tbody
	- @sites.each do |site|
		= content_tag_for(:tr, site) do
			%td= link_to site.name, admin_site_path(site)
			%td= site.uuid
			%td= site.domain
			%td= link_to "Edit", edit_admin_site_path(site)

app/views/admin/sites/new.html.haml
= form_for @site, :url => admin_sites_path do |f|
	= render :partial => 'form', :locals => {:f => f}

app/views/admin/sites/show.html.haml
- content_for :title_header do
	= link_to "Edit Site", edit_admin_site_path(@site), :class => "btn", :style => "float: right; position: relative; top: -45px;"

	= form_tag admin_site_path(@site), :method => :get, :style => "margin-right: 15px; float: right; position: relative; top: -45px;" do
		= text_field_tag :search, params[:search], :placeholder => "Search URLs", :style => "width: 125px"

.well.span11
	<b>Tweetbot Custom URL Shortener:</b> http://#{@site.domain}/api/#{@site.uuid}/urls/new?url=%@

%table.table.table-striped.table-bordered
	%thead
		%tr
			%th Long URL
			%th Short URL
			%th Clicks
			%th
	%tbody
		- if @urls.present?
			= render @urls
		- else
			%tr
				%td{:colspan => "4", :style => "text-align: center; font-style: italic;"} No URLs Found

= will_paginate @urls

app/views/admin/urls/_url.html.haml
= content_tag_for(:tr, url) do
	%td.long_url
		%b= url.title
		%p= url.long_url
	%td= link_to url.full_short_link, url.full_short_link
	%td
		- if url.created_at.nil?
			= url.old_clicks
		- else
			= link_to url.clicks.size, clicks_admin_url_path(url)

	%td= link_to "X", admin_url_path(url), :method => :delete, :data => {:confirm => "Are you sure?"}

app/views/admin/urls/clicks.html.haml
%table.table.table-striped.table-bordered
	%thead
		%tr
			%th IP Address
			%th Referrer
			%th User Agent
			%th Date/Time
	%tbody
		- @clicks.each do |click|
			= content_tag_for(:tr, click) do
				%td= click.ip_address
				%td.referrer
					%p= click.referrer
				%td.user_agent
					%p= click.user_agent
				%td= click.created_at.strftime("%e/%m/%y - %H:%M")

app/views/admin/urls/index.html.haml
- content_for :title_header do
	= form_tag admin_urls_path, :method => :get, :style => "float: right; position: relative; top: -45px;" do
		= text_field_tag :search, params[:search], :placeholder => "Search URLs", :style => "width: 125px"


%table.table.table-striped.table-bordered
	%thead
		%tr
			%th Long URL
			%th Short URL
			%th Clicks
			%th
	%tbody
		= render @urls

= will_paginate @urls